# Configuration file for IgnorePlayer by Rushil13579 | Rushil#2326

# Version [DO NOT TOUCH]
version: 1.1.0

# If ignoring a player prevents messages from them [true => enabled, false => disabled]
ignore-private-message: true